export interface RegionGroup {
  label: string;
  regions: string[];
}

export const BIH_REGION_GROUPS: RegionGroup[] = [
  {
    label: "Unsko-sanski kanton",
    regions: [
      "Unsko-sanski kanton",
      "Bihać",
      "Bosanska Krupa",
      "Bosanski Petrovac",
      "Bužim",
      "Cazin",
      "Ključ",
      "Sanski Most",
      "Velika Kladuša",
    ],
  },
  {
    label: "Posavski kanton",
    regions: ["Posavski kanton", "Domaljevac-Šamac", "Odžak", "Orašje"],
  },
  {
    label: "Tuzlanski kanton",
    regions: [
      "Tuzlanski kanton",
      "Banovići",
      "Čelić",
      "Doboj Istok",
      "Gračanica",
      "Gradačac",
      "Kalesija",
      "Kladanj",
      "Lukavac",
      "Sapna",
      "Srebrenik",
      "Teočak",
      "Tuzla",
      "Živinice",
    ],
  },
  {
    label: "Zeničko-dobojski kanton",
    regions: [
      "Zeničko-dobojski kanton",
      "Breza",
      "Doboj Jug",
      "Kakanj",
      "Maglaj",
      "Olovo",
      "Tešanj",
      "Usora",
      "Vareš",
      "Visoko",
      "Zavidovići",
      "Zenica",
      "Žepče",
    ],
  },
  {
    label: "Bosansko-podrinjski kanton",
    regions: ["Bosansko-podrinjski kanton", "Foča-Ustikolina", "Goražde", "Pale-Prača"],
  },
  {
    label: "Srednjobosanski kanton",
    regions: [
      "Srednjobosanski kanton",
      "Bugojno",
      "Busovača",
      "Dobretići",
      "Donji Vakuf",
      "Fojnica",
      "Gornji Vakuf-Uskoplje",
      "Jajce",
      "Kiseljak",
      "Kreševo",
      "Novi Travnik",
      "Travnik",
      "Vitez",
    ],
  },
  {
    label: "Hercegovačko-neretvanski kanton",
    regions: [
      "Hercegovačko-neretvanski kanton",
      "Čapljina",
      "Čitluk",
      "Jablanica",
      "Konjic",
      "Mostar",
      "Neum",
      "Prozor-Rama",
      "Ravno",
      "Stolac",
    ],
  },
  {
    label: "Zapadnohercegovački kanton",
    regions: ["Zapadnohercegovački kanton", "Grude", "Ljubuški", "Posušje", "Široki Brijeg"],
  },
  {
    label: "Kanton Sarajevo",
    regions: [
      "Kanton Sarajevo",
      "Sarajevo",
      "Centar Sarajevo",
      "Hadžići",
      "Ilidža",
      "Ilijaš",
      "Novi Grad Sarajevo",
      "Novo Sarajevo",
      "Stari Grad Sarajevo",
      "Trnovo (FBiH)",
      "Vogošća",
    ],
  },
  {
    label: "Kanton 10",
    regions: [
      "Kanton 10",
      "Bosansko Grahovo",
      "Drvar",
      "Glamoč",
      "Kupres",
      "Livno",
      "Tomislavgrad",
    ],
  },
  {
    label: "Brčko distrikt",
    regions: ["Brčko distrikt", "Brčko"],
  },
  {
    label: "Republika Srpska · Krajina i Banja Luka",
    regions: [
      "Banja Luka",
      "Čelinac",
      "Gradiška",
      "Jezero",
      "Kneževo",
      "Kostajnica",
      "Kotor Varoš",
      "Kozarska Dubica",
      "Krupa na Uni",
      "Kupres (RS)",
      "Laktaši",
      "Mrkonjić Grad",
      "Novi Grad",
      "Oštra Luka",
      "Petrovac",
      "Prijedor",
      "Prnjavor",
      "Ribnik",
      "Srbac",
      "Šipovo",
    ],
  },
  {
    label: "Republika Srpska · Doboj, Posavina i Semberija",
    regions: [
      "Bijeljina",
      "Brod",
      "Derventa",
      "Doboj",
      "Donji Žabar",
      "Lopare",
      "Modriča",
      "Osmaci",
      "Pelagićevo",
      "Petrovo",
      "Šamac",
      "Stanari",
      "Teslić",
      "Ugljevik",
      "Vukosavlje",
      "Zvornik",
    ],
  },
  {
    label: "Republika Srpska · Romanija i Podrinje",
    regions: [
      "Istočno Sarajevo",
      "Istočna Ilidža",
      "Istočno Novo Sarajevo",
      "Istočni Stari Grad",
      "Pale",
      "Sokolac",
      "Trnovo (RS)",
      "Bratunac",
      "Čajniče",
      "Foča",
      "Han Pijesak",
      "Kalinovik",
      "Milići",
      "Novo Goražde",
      "Rogatica",
      "Rudo",
      "Srebrenica",
      "Šekovići",
      "Višegrad",
      "Vlasenica",
    ],
  },
  {
    label: "Republika Srpska · Hercegovina",
    regions: [
      "Berkovići",
      "Bileća",
      "Gacko",
      "Istočni Drvar",
      "Istočni Mostar",
      "Ljubinje",
      "Nevesinje",
      "Trebinje",
    ],
  },
];

export const BIH_REGIONS = [...new Set(BIH_REGION_GROUPS.flatMap((group) => group.regions))];
